import type { Metadata } from "next";
import { Fredoka  } from "next/font/google";
import "./globals.css";

const fredoka = Fredoka({
  variable: "--font-fredoka-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});




export const metadata: Metadata = {
  title: "Wiki-Cat Rush",
  description: "Generated by Wiki Cat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fredoka.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
